vaadin.productionMode=false
vaadin.launch-browser=true
server.port=8081

halo.upload.root-directory=./data/hr/uploads

#logging.level.root=INFO
#logging.level.org.halocambodia=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE

app.thumbnail.video.enabled=true
app.thumbnail.video.ffmpeg-path=${user.dir}/ffmpeg/bin/ffmpeg.exe