# Log the SQL queries
log4jdbc.spylogdelegator.name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator

# Enable stack trace for SQL statements (shows line number)
log4jdbc.dump.sql.maxlinelength=1000
log4jdbc.dump.sql.showlinenum=true
log4jdbc.dump.sql.timestamp=true
log4jdbc.dump.sql.select=true
log4jdbc.dump.sql.insert=true
log4jdbc.dump.sql.update=true
log4jdbc.dump.sql.delete=true
